library(data.table)
library(shiny)
library(shinydashboard)
library(dplyr)
library(shinyWidgets)
library(jsonlite)
library(mongolite)






# TO DO : 
# REPARER LA PAGE D'ACCUEIL MAUVAISE AUTHENTIFICATION
# RECUPERER TOUTES LES SAUVEGARDES ET LAISSER L'UTILISATEUR CHOISIR PAR DATE DE SAUVEGARDE
# RECUPERER LA DERNIERE SAUVEGARDE DU FORMULAIRE
# REMPLIR LES CHAMPS AVEC LA DERNIERE SAUVEGARDE
# REALISER UNE SAUVEGARDE AUTOMATIQUE
